import { Box, Button, Container, Text } from '@chakra-ui/react';
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import useCountdown from '@components/useCountdown'
// import styles from '../styles/Home.module.css'

export default function Home() {

  const { ticking, start, stop, reset, timeLeft, progress } = useCountdown({
    minutes: 1,
    onStart: () => {
      // updateFavicon(mode);
      console.log('started')
    },
    onStop: () => {
      // updateFavicon();
      console.log('ended')
    },
    onComplete: () => {
      next();
      // alarmAudio.play();
      console.log('completed')
    },
  });

  const formatTime = (time) => {
    let minutes = "00";
    if (time >= 60) {
      minutes = Math.floor(time / 60).toString()
      minutes = minutes.length === 1 ? "0" + minutes : minutes
    }
    let seconds = (time - Math.floor(time / 60) * 60).toString()
    seconds = seconds.length === 1 ? "0" + seconds : seconds
    return minutes + ":" + seconds
  }

  return (
    <div className="HEader">
      <Head>
        <title>{ticking && formatTime(timeLeft) + " Interval Timer"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        pt="10"
        align="center"
        justify="space-between">

        <Box>
          <Text fontSize="6xl">{formatTime(timeLeft)}</Text>
        </Box>
        <Button onClick={ticking ? stop : start}>
          {ticking ? "Stop" : "Start"}
        </Button>
        <Button onClick={reset}>
          Reset
        </Button>
      </Container>


    </div>
  )
}
